// Mozilla User Preferences

// DO NOT EDIT THIS FILE.
//
// If you make changes to this file while the application is running,
// the changes will be overwritten when the application exits.
//
// To change a preference value, you can either:
// - modify it via the UI (e.g. via about:config in the browser); or
// - set it within a user.js file in your profile.

user_pref("app.normandy.first_run", false);
user_pref("app.normandy.startupExperimentPrefs.dom.push.alwaysConnect", true);
user_pref("app.normandy.startupExperimentPrefs.network.http.spdy.websockets", false);
user_pref("app.normandy.user_id", "069125b7-a871-4960-b2ec-fba4e91fd0cc");
user_pref("app.update.lastUpdateTime.addon-background-update-timer", 1549032300);
user_pref("app.update.lastUpdateTime.blocklist-background-update-timer", 1549032420);
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 1549031820);
user_pref("app.update.lastUpdateTime.recipe-client-addon-run", 1549032060);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 1549031940);
user_pref("app.update.lastUpdateTime.services-settings-poll-changes", 1549032180);
user_pref("app.update.lastUpdateTime.telemetry_modules_ping", 1549032660);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 1549032540);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.cache.disk.capacity", 378880);
user_pref("browser.cache.disk.filesystem_reported", 1);
user_pref("browser.cache.disk.smart_size.first_run", false);
user_pref("browser.contentblocking.category", "standard");
user_pref("browser.laterrun.bookkeeping.profileCreationTime", 1549031791);
user_pref("browser.laterrun.bookkeeping.sessionCount", 1);
user_pref("browser.laterrun.enabled", true);
user_pref("browser.migration.version", 77);
user_pref("browser.newtabpage.activity-stream.impressionId", "{61ebcd70-e601-448e-988a-6709e9086dd3}");
user_pref("browser.newtabpage.activity-stream.migrationLastShownDate", 1548957600);
user_pref("browser.newtabpage.activity-stream.migrationRemainingDays", 3);
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.pageActions.persistedActions", "{\"version\":1,\"ids\":[\"bookmark\",\"bookmarkSeparator\",\"copyURL\",\"emailLink\",\"addSearchEngine\",\"sendToDevice\",\"pocket\",\"screenshots_mozilla_org\"],\"idsInUrlbar\":[\"pocket\",\"bookmark\"]}");
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.safebrowsing.provider.google4.lastupdatetime", "1549033619731");
user_pref("browser.safebrowsing.provider.google4.nextupdatetime", "1549035443731");
user_pref("browser.safebrowsing.provider.mozilla.lastupdatetime", "1549031806702");
user_pref("browser.safebrowsing.provider.mozilla.nextupdatetime", "1549035406702");
user_pref("browser.search.region", "KZ");
user_pref("browser.shell.mostRecentDateSetAsDefault", "1549031801");
user_pref("browser.slowStartup.averageTime", 15095);
user_pref("browser.slowStartup.samples", 1);
user_pref("browser.startup.homepage_override.buildID", "20190128144255");
user_pref("browser.startup.homepage_override.mstone", "65.0");
user_pref("browser.uiCustomization.state", "{\"placements\":{\"widget-overflow-fixed-list\":[],\"nav-bar\":[\"back-button\",\"forward-button\",\"stop-reload-button\",\"home-button\",\"customizableui-special-spring1\",\"urlbar-container\",\"customizableui-special-spring2\",\"downloads-button\",\"library-button\",\"sidebar-button\"],\"toolbar-menubar\":[\"menubar-items\"],\"TabsToolbar\":[\"tabbrowser-tabs\",\"new-tab-button\",\"alltabs-button\"],\"PersonalToolbar\":[\"personal-bookmarks\"]},\"seen\":[\"developer-button\"],\"dirtyAreaCache\":[\"nav-bar\"],\"currentVersion\":15,\"newElementCount\":2}");
user_pref("browser.urlbar.placeholderName", "Google");
user_pref("browser.urlbar.timesBeforeHidingSuggestionsHint", 2);
user_pref("datareporting.policy.dataSubmissionPolicyAcceptedVersion", 2);
user_pref("datareporting.policy.dataSubmissionPolicyNotifiedTime", "1549031803257");
user_pref("devtools.onboarding.telemetry.logged", true);
user_pref("distribution.canonical.bookmarksProcessed", true);
user_pref("distribution.iniFile.exists.appversion", "65.0");
user_pref("distribution.iniFile.exists.value", true);
user_pref("dom.push.userAgentID", "f9c579e982d14f9ba24fc15bb159193f");
user_pref("extensions.blocklist.lastModified", "Mon, 28 Jan 2019 18:12:57 GMT");
user_pref("extensions.blocklist.pingCountTotal", 2);
user_pref("extensions.blocklist.pingCountVersion", 2);
user_pref("extensions.databaseSchema", 28);
user_pref("extensions.getAddons.cache.lastUpdate", 1549032330);
user_pref("extensions.getAddons.databaseSchema", 5);
user_pref("extensions.lastAppVersion", "65.0");
user_pref("extensions.lastPlatformVersion", "65.0");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.systemAddonSet", "{\"schema\":1,\"directory\":\"{09859d39-5ae9-4319-b2a2-1507829119b1}\",\"addons\":{\"fxmonitor@mozilla.org\":{\"version\":\"2.8\"}}}");
user_pref("extensions.webcompat.perform_injections", true);
user_pref("extensions.webcompat.perform_ua_overrides", true);
user_pref("extensions.webextensions.uuids", "{\"formautofill@mozilla.org\":\"c3db3c5d-7e4e-4b7d-9ecb-d1dbbf90108d\",\"screenshots@mozilla.org\":\"6d90201e-85d2-4c4a-979b-3b2e38a46109\",\"webcompat-reporter@mozilla.org\":\"e16c0f43-14b3-441e-998d-8d28d29c02fc\",\"webcompat@mozilla.org\":\"1a0c2db8-4a1a-446b-9cea-8bdc4081809a\",\"fxmonitor@mozilla.org\":\"22b258ae-60a7-46a7-819f-03f2a98e45a4\"}");
user_pref("lightweightThemes.usedThemes", "[]");
user_pref("media.gmp-gmpopenh264.abi", "x86_64-gcc3");
user_pref("media.gmp-gmpopenh264.lastUpdate", 1549031872);
user_pref("media.gmp-gmpopenh264.version", "1.7.1");
user_pref("media.gmp-manager.buildID", "20190128144255");
user_pref("media.gmp-manager.lastCheck", 1549031871);
user_pref("media.gmp.storage.version.observed", 1);
user_pref("network.predictor.cleaned-up", true);
user_pref("pdfjs.enabledCache.state", true);
user_pref("pdfjs.migrationVersion", 2);
user_pref("pdfjs.previousHandler.alwaysAskBeforeHandling", true);
user_pref("pdfjs.previousHandler.preferredAction", 4);
user_pref("places.history.expiration.transient_current_max_pages", 105054);
user_pref("plugin.disable_full_page_plugin_for_types", "application/pdf");
user_pref("privacy.sanitize.pending", "[{\"id\":\"newtab-container\",\"itemsToClear\":[],\"options\":{}}]");
user_pref("security.sandbox.content.tempDirSuffix", "acb1ca51-6abf-4998-ba3b-35d74bcd774e");
user_pref("security.sandbox.plugin.tempDirSuffix", "e6ff3cf7-f952-48bb-b4cd-5e71edccd713");
user_pref("services.blocklist.addons.checked", 1549032082);
user_pref("services.blocklist.gfx.checked", 1549032082);
user_pref("services.blocklist.onecrl.checked", 1549032082);
user_pref("services.blocklist.pinning.checked", 1549032082);
user_pref("services.blocklist.plugins.checked", 1549032082);
user_pref("services.settings.clock_skew_seconds", -252);
user_pref("services.settings.last_etag", "\"1548796224519\"");
user_pref("services.settings.last_update_seconds", 1549032432);
user_pref("services.settings.main.language-dictionaries.last_check", 1549032082);
user_pref("services.settings.main.onboarding.last_check", 1549032082);
user_pref("services.settings.main.sites-classification.last_check", 1549032082);
user_pref("signon.importedFromSqlite", true);
user_pref("toolkit.startup.last_success", 1549031784);
user_pref("toolkit.telemetry.cachedClientID", "badd5e85-dd10-400a-b5f9-e50dd44ecd3a");
user_pref("toolkit.telemetry.previousBuildID", "20190128144255");
user_pref("toolkit.telemetry.reportingpolicy.firstRun", false);
